trigger:
- main

pool:
  name: ven-pool

steps:
- script: echo Hello, world!
  displayName: 'stage-1'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'stage-2'

- script:  echo "welcome"
  displayName: 'stage-3'

- script:  echo "hi, hello"
  displayName: 'stage-4'
